---
permalink: intro-family.html 
keywords: introduction, what is ONTAP systems, AFF, FAS, ASA, all-flash, ONTAP 
summary: La familia de sistemas de almacenamiento ONTAP de NetApp está diseñada para aplicaciones empresariales que necesitan un almacenamiento fácil de gestionar, rápido y seguro, con fiabilidad empresarial y un acceso continuo a los datos. 
---
= Obtenga información sobre los sistemas de hardware de ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


Los sistemas de hardware ONTAP de NetApp están diseñados para aplicaciones empresariales que necesitan un almacenamiento fácil de gestionar, rápido y seguro con fiabilidad de nivel empresarial y un acceso continuo a los datos.

Los sistemas de hardware ONTAP de NetApp están disponibles en configuraciones all-flash (AFF) y de flash híbrido y solo HDD (FAS), lo que le ofrece la opción de elegir la combinación de medios de almacenamiento que mejor satisfaga sus requisitos de rendimiento, capacidad y coste.

Puede agrupar diferentes combinaciones de modelos para ejecutar cargas de trabajo mixtas en el mismo sistema de almacenamiento y desarrollar su entorno agregando nuevas generaciones de almacenamiento con las tecnologías más recientes.



== Sistemas All Flash FAS (AFF)

Los sistemas AFF basados en NVMe son una plataforma robusta de escalado horizontal creada para entornos virtualizados y se pueden poner en marcha como un sistema independiente o como un nivel de alto rendimiento en una configuración ONTAP de NetApp.

Las configuraciones FAS All-Flash dan soporte a una amplia gama de cargas de trabajo, especialmente VDI y bases de datos que requieren un alto rendimiento, una baja latencia y fiabilidad.

https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["Lea las especificaciones técnicas de AFF A-Series"^] y.. https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["Lea las especificaciones técnicas de la serie C de AFF"^].



== Sistemas de cabinas All SAN (ASA)

La cabina SAN All-Flash (ASA) de NetApp facilita una experiencia SAN simplificada y dedicada que ofrece disponibilidad continua de datos para bases de datos de misión crítica para la empresa y otras cargas de trabajo SAN mediante el protocolo iSCSI o la certificación FCP.

https://www.netapp.com/pdf.html?item=/media/19466-SB-4081.pdf["Lea las especificaciones técnicas de ASA"^]



== Sistemas híbridos con flash FAS

Los sistemas de flash híbrido FAS son una plataforma de hardware creada para entornos SAN y NAS compartidos y consolidados que requieren la gestión de datos enriquecidos y fácil conexión al cloud.

Con su hardware de alta disponibilidad, los sistemas flash híbrido FAS satisfacen de forma rentable las demandas de las cargas de trabajo mediante la combinación ideal de unidades flash y de disco giratorio tradicionales. Es perfecto para backup y retención, consolidación de aplicaciones empresariales de uso general y contenido distribuido.

https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Lea las especificaciones técnicas de FAS"^]



== MetroCluster

Los sistemas de almacenamiento de hardware de ONTAP configurados con la funcionalidad MetroCluster de ONTAP brindan una solución que combina clustering basado en arreglos con replicación síncrona para ofrecer disponibilidad continua y cero pérdida de datos. La configuración de MetroCluster duplica de forma inmediata todos los datos de misión crítica transacción por transacción, con lo que proporciona acceso ininterrumpido a las aplicaciones y los datos.

A diferencia de las soluciones de replicación de datos convencionales, MetroCluster funciona sin problemas con el entorno del host para ofrecer disponibilidad de datos continua y eliminar, al mismo tiempo, la necesidad de crear y mantener scripts complejos de conmutación al nodo de respaldo.

https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["Más información acerca de MetroCluster"^]



== Software ONTAP

El software para la gestión de datos ONTAP es el software de almacenamiento en clúster que activa los sistemas de hardware ONTAP. Con un espacio de nombres global que admite hasta 24 nodos de hardware de todos los tipos, el software ONTAP admite almacenamiento unificado (bloque y archivo), lo que permite la consolidación significativa de cargas de trabajo que se pueden gestionar mediante la interfaz gráfica de usuario de ONTAP System Manager.

https://www.netapp.com/pdf.html?item=/media/7413-ds-3231.pdf["Lea las especificaciones técnicas de ONTAP"^].



== Si quiere más información

* https://docs.netapp.com/us-en/ontap-systems/index.html["Documentos de AFF y FAS"^]
* https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentos de MetroCluster"^]
* https://docs.netapp.com/us-en/ontap/index.html["Documentos de ONTAP"^]

