---
permalink: intro-family.html 
keywords: introduction, what is ONTAP systems, AFF, AFX, FAS, ASA, all-flash, ONTAP 
summary: La familia de sistemas de almacenamiento ONTAP de NetApp está diseñada para aplicaciones empresariales que necesitan un almacenamiento fácil de gestionar, rápido y seguro, con fiabilidad empresarial y un acceso continuo a los datos. 
---
= Obtenga información sobre los sistemas de hardware de ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Los sistemas de hardware ONTAP de NetApp están diseñados para aplicaciones empresariales que necesitan un almacenamiento fácil de gestionar, rápido y seguro con fiabilidad de nivel empresarial y un acceso continuo a los datos.

Los sistemas de hardware ONTAP de NetApp están disponibles en configuraciones all-flash, flash híbrido y solo HDD, lo que le brinda la opción de elegir la combinación de medios de almacenamiento que mejor se adapte a sus requisitos de rendimiento, capacidad y costo.

Puede agrupar diferentes combinaciones de modelos para ejecutar cargas de trabajo mixtas en el mismo sistema de almacenamiento y desarrollar su entorno agregando nuevas generaciones de almacenamiento con las tecnologías más recientes.



== Sistemas All Flash FAS (AFF)

Los sistemas AFF basados en NVMe son una plataforma robusta de escalado horizontal creada para entornos virtualizados y se pueden poner en marcha como un sistema independiente o como un nivel de alto rendimiento en una configuración ONTAP de NetApp.

Las configuraciones FAS All-Flash dan soporte a una amplia gama de cargas de trabajo, especialmente VDI y bases de datos que requieren un alto rendimiento, una baja latencia y fiabilidad.

* https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["Lea las especificaciones técnicas De A-Series de AFF"^]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["Lea las especificaciones técnicas de C-Series de AFF"^]




== AFX

NetApp AFX es un sistema de almacenamiento all-flash desagregado de nivel empresarial que ofrece todos los beneficios de rendimiento de los sistemas de archivos paralelos y las soluciones de almacenamiento de IA de nicho, pero en una plataforma de nivel empresarial que es simple, segura y completamente integrada.

* https://www.netapp.com/pdf.html?item=/media/142853-ds-3466-netapp-afx-datasheet.pdf["Lea la hoja de datos de AFX"^]
* https://docs.netapp.com/us-en/ontap-afx/get-started/ontap-afx-storage.html["Obtenga más información sobre el almacenamiento AFX"^]




== Sistemas de cabinas All Flash SAN (ASA)

La cabina SAN All-Flash (ASA) de NetApp facilita una experiencia SAN simplificada y dedicada que ofrece disponibilidad continua de datos para bases de datos de misión crítica para la empresa y otras cargas de trabajo SAN mediante el protocolo iSCSI o la certificación FCP.

.Sistemas ASA r2
Los nuevos sistemas NetApp ASA r2 (ASA A1K, ASA A70, ASA A90, ASA A20, ASA A30, ASA A50 y C30) ofrecen una solución unificada de hardware y software que crea una experiencia simplificada específica para las necesidades de los clientes que solo utilizan SAN.

En un sistema ASA R2, se han optimizado el software ONTAP y System Manager para proporcionar compatibilidad con las funciones SAN esenciales mientras se elimina la visibilidad de las características y funciones no compatibles con los entornos SAN.

* https://www.netapp.com/data-storage/all-flash-san-storage-array/["Lea las especificaciones técnicas de ASA"^]
* Obtenga más información acerca de link:https://docs.netapp.com/us-en/asa-r2/learn-more/hardware-comparison.html["Nuevos sistemas R2 de ASA en comparación con los sistemas ASA"^]
* Vea todas las limitaciones y compatibilidad de la configuración de los sistemas ASA y ASA R2 en https://hwu.netapp.com/["NetApp Hardware Universe"^]




== Sistemas híbridos con flash FAS

Los sistemas de flash híbrido FAS son una plataforma de hardware creada para entornos SAN y NAS compartidos y consolidados que requieren la gestión de datos enriquecidos y fácil conexión al cloud.

Con su hardware de alta disponibilidad, los sistemas flash híbrido FAS satisfacen de forma rentable las demandas de las cargas de trabajo mediante la combinación ideal de unidades flash y de disco giratorio tradicionales. Es perfecto para backup y retención, consolidación de aplicaciones empresariales de uso general y contenido distribuido.

https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Lea las especificaciones técnicas de FAS"^]



== MetroCluster

Los sistemas de almacenamiento de hardware de ONTAP configurados con la funcionalidad MetroCluster de ONTAP brindan una solución que combina clustering basado en arreglos con replicación síncrona para ofrecer disponibilidad continua y cero pérdida de datos. La configuración de MetroCluster duplica de forma inmediata todos los datos de misión crítica transacción por transacción, con lo que proporciona acceso ininterrumpido a las aplicaciones y los datos.

A diferencia de las soluciones de replicación de datos convencionales, MetroCluster funciona sin problemas con el entorno del host para ofrecer disponibilidad de datos continua y eliminar, al mismo tiempo, la necesidad de crear y mantener scripts complejos de conmutación al nodo de respaldo.

https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["Obtenga más información acerca de MetroCluster"^]



== Software ONTAP

El software para la gestión de datos ONTAP es el software de almacenamiento en clúster que activa los sistemas de hardware ONTAP. Con un espacio de nombres global que admite hasta 24 nodos de hardware de todos los tipos, el software ONTAP admite almacenamiento unificado (bloque y archivo), lo que permite la consolidación significativa de cargas de trabajo que se pueden gestionar mediante la interfaz gráfica de usuario de ONTAP System Manager.

https://www.netapp.com/pdf.html?item=/media/7413-ds-3231.pdf["Lea las especificaciones técnicas del software ONTAP"^]

.Si quiere más información
* https://docs.netapp.com/us-en/ontap-systems/index.html["Documentos de los sistemas de hardware de ONTAP"^]
* https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentos de MetroCluster"^]
* https://docs.netapp.com/us-en/ontap/index.html["Documentos de ONTAP"^]

