---
settings:
  name: ONTAP hardware systems
  search: ontap-systems,ontap-systems-upgrade,ontap-systems-switches,ontap-metrocluster
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentación de los sistemas de hardware de ONTAP
    url: "/index.html"
